Ashwini_Assignment_35
KrishnaKTechnocredits/Jan24_Java pull request #955
Opened 2024-02-04 14:58 UTC by AshwiniBalki

### Assignment Number :35

### Assignment Description :notebook:
Assignment - 35 : 4th Feb'2024
Return the sum of even index [0,2,4,6]
input : {3, 6, 9, 11, 15, 20, 4, 26}
Output : 60
hint 6, 20, 4, 26

### Evidence :file_folder:
![image](https://github.com/KrishnaKTechnocredits/Jan24_Java/assets/15879612/e09559bc-b4a4-4b6d-883d-a42212c2b9c2)

### Checklist before requesting a review :ballot_box_with_check:

- [x] I have performed a self-review of my code
- [x] My changes generate no compile time errors

2024-02-05 13:12 UTC, MargiVegada requested changes
Incorrect evidence

2024-02-05 13:12 UTC, MargiVegada commented on src/ashwini_b/SumOfEvenIndex.java
> +				// System.out.println(num[index]);
Don't push unnecessary commented code

2024-02-05 13:12 UTC, MargiVegada commented on src/ashwini_b/SumOfEvenIndex.java
> +			if (index % 2 == 0 || index == 0) {
Why you add this condition index==0

2024-02-09 17:08 UTC, AshwiniBalki commented on src/ashwini_b/SumOfEvenIndex.java
> +				// System.out.println(num[index]);
removed comment.

2024-02-09 17:09 UTC, AshwiniBalki commented on src/ashwini_b/SumOfEvenIndex.java
> +			if (index % 2 == 0 || index == 0) {
removed condition.

2024-02-10 11:35 UTC, merged